# Dump event info
name: event

on:
  pull_request_target:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  build:
    name: ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Event data
        run: cat "${{ github.event_path }}"
      - name: Get commit info
        run: |
          echo "${{ github.token }}" | gh auth login --with-token
          issue_timeline_url="$(jq -r .issue_url "${{ github.event_path }}")/timeline"
          issue_timeline=$(gh api issue_timeline_url)
          echo "$issue_timeline" | jq -r .commit_id
          echo "$issue_timeline" | jq -r .commit_url
          
